visual-tests:
  image: mcr.microsoft.com/playwright:v1.58.2-jammy
  script:
    - npm ci
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - applitools.log
    expire_in: 7 days
